/**
 * Auto-Generated Plugin Registry
 * Generated: 2025-11-20T03:48:45.166Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'pnpm discover-plugins' to regenerate
 */

// Address (enabled)
// Authentication (enabled)
// Blog (enabled)
// Calendar (enabled)
// Chat (enabled)
// Checkout (enabled)
// Dashboard (enabled)
// Analytics Plugin (enabled)
// File Manager (enabled)
// Invoice (enabled)
// Job Board (enabled)
// Kanban Board (enabled)
// Mail (enabled)
// y (enabled)
// Order Management (enabled)
// Payment (enabled)
// Product (enabled)
// Tour (enabled)
// User Management (enabled)

/**
 * List of all discovered plugin IDs
 */
export const discoveredPluginIds = [
  'address',
  'auth',
  'blog',
  'calendar',
  'chat',
  'checkout',
  'dashboard',
  'analytics-plugin',
  'file-manager',
  'invoice',
  'job',
  'kanban',
  'mail',
  'my-awesome-plugin',
  'order',
  'payment',
  'product',
  'tour',
  'user'
] as const;

/**
 * Plugin metadata
 */
export const pluginMetadata = [
  {
    "id": "address",
    "name": "Address",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/address"
  },
  {
    "id": "auth",
    "name": "Authentication",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/auth"
  },
  {
    "id": "blog",
    "name": "Blog",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/blog"
  },
  {
    "id": "calendar",
    "name": "Calendar",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/calendar"
  },
  {
    "id": "chat",
    "name": "Chat",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/chat"
  },
  {
    "id": "checkout",
    "name": "Checkout",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/checkout"
  },
  {
    "id": "dashboard",
    "name": "Dashboard",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/dashboard"
  },
  {
    "id": "analytics-plugin",
    "name": "Analytics Plugin",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/example-analytics"
  },
  {
    "id": "file-manager",
    "name": "File Manager",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/file-manager"
  },
  {
    "id": "invoice",
    "name": "Invoice",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/invoice"
  },
  {
    "id": "job",
    "name": "Job Board",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/job"
  },
  {
    "id": "kanban",
    "name": "Kanban Board",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/kanban"
  },
  {
    "id": "mail",
    "name": "Mail",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/mail"
  },
  {
    "id": "my-awesome-plugin",
    "name": "y",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/my-awesome-plugin"
  },
  {
    "id": "order",
    "name": "Order Management",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/order"
  },
  {
    "id": "payment",
    "name": "Payment",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/payment"
  },
  {
    "id": "product",
    "name": "Product",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/product"
  },
  {
    "id": "tour",
    "name": "Tour",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/tour"
  },
  {
    "id": "user",
    "name": "User Management",
    "version": "1.0.0",
    "enabled": true,
    "path": "packages/features/user"
  }
];

/**
 * Get plugin import path
 */
export function getPluginImportPath(pluginId: string): string {
  const plugin = pluginMetadata.find((p) => p.id === pluginId);
  if (!plugin) {
    throw new Error(`Plugin "${pluginId}" not found`);
  }
  return `@app/${pluginId}`;
}

/**
 * Check if plugin is discovered
 */
export function isPluginDiscovered(pluginId: string): boolean {
  return pluginMetadata.some((p) => p.id === pluginId);
}

/**
 * Get all enabled plugin IDs
 */
export function getEnabledPluginIds(): string[] {
  return pluginMetadata.filter((p) => p.enabled).map((p) => p.id);
}
