#!/usr/bin/env node

/**
 * Plugin Discovery Script
 * Scans packages/features for plugins and generates a plugins manifest
 *
 * Usage:
 *   node scripts/discover-plugins.js
 *   pnpm discover-plugins
 */

const fs = require('fs');
const path = require('path');

/**
 * Discover all plugins in the features directory
 */
function discoverPlugins() {
  const featuresDir = path.join(__dirname, '..', 'packages', 'features');

  if (!fs.existsSync(featuresDir)) {
    console.error('❌ Features directory not found:', featuresDir);
    process.exit(1);
  }

  const plugins = [];
  const pluginDirs = fs.readdirSync(featuresDir);

  console.log('🔍 Discovering plugins...\n');

  pluginDirs.forEach((dir) => {
    const pluginPath = path.join(featuresDir, dir);
    const manifestPath = path.join(pluginPath, 'plugin.json');
    const indexPath = path.join(pluginPath, 'index.ts');

    // Skip if not a directory
    if (!fs.statSync(pluginPath).isDirectory()) {
      return;
    }

    // Check for manifest
    if (!fs.existsSync(manifestPath)) {
      console.log(`⚠️  ${dir}: No plugin.json found`);
      return;
    }

    // Check for index.ts
    if (!fs.existsSync(indexPath)) {
      console.log(`⚠️  ${dir}: No index.ts found`);
      return;
    }

    try {
      const manifestContent = fs.readFileSync(manifestPath, 'utf-8');
      const manifest = JSON.parse(manifestContent);

      // Validate required fields
      if (!manifest.id || !manifest.name || !manifest.version) {
        console.log(`❌ ${dir}: Invalid manifest (missing id, name, or version)`);
        return;
      }

      plugins.push({
        id: manifest.id,
        name: manifest.name,
        version: manifest.version,
        enabled: manifest.enabled !== false,
        path: `packages/features/${dir}`,
        manifestPath: `packages/features/${dir}/plugin.json`,
        indexPath: `packages/features/${dir}/index.ts`,
      });

      console.log(
        `${manifest.enabled !== false ? '✅' : '❌'} ${manifest.name} (${manifest.id}) v${manifest.version}`
      );
    } catch (error) {
      console.log(`❌ ${dir}: Error parsing manifest - ${error.message}`);
    }
  });

  return plugins;
}

/**
 * Generate plugins manifest file
 */
function generateManifest(plugins) {
  const outputPath = path.join(__dirname, '..', 'packages', 'core', 'config', 'src', 'plugins', 'discovered-plugins.json');

  const manifest = {
    generated: new Date().toISOString(),
    total: plugins.length,
    enabled: plugins.filter((p) => p.enabled).length,
    disabled: plugins.filter((p) => !p.enabled).length,
    plugins,
  };

  fs.writeFileSync(outputPath, JSON.stringify(manifest, null, 2));

  console.log(`\n📄 Generated: ${outputPath}`);
  return outputPath;
}

/**
 * Generate TypeScript import file
 */
function generateImports(plugins) {
  const outputPath = path.join(
    __dirname,
    '..',
    'packages',
    'core',
    'config',
    'src',
    'plugins',
    'auto-discovered-plugins.ts'
  );

  const imports = plugins
    .map((p) => `// ${p.name} (${p.enabled ? 'enabled' : 'disabled'})`)
    .join('\n');

  const pluginIds = plugins
    .filter((p) => p.enabled)
    .map((p) => `  '${p.id}'`)
    .join(',\n');

  const content = `/**
 * Auto-Generated Plugin Registry
 * Generated: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'pnpm discover-plugins' to regenerate
 */

${imports}

/**
 * List of all discovered plugin IDs
 */
export const discoveredPluginIds = [
${pluginIds}
] as const;

/**
 * Plugin metadata
 */
export const pluginMetadata = ${JSON.stringify(
    plugins.map((p) => ({
      id: p.id,
      name: p.name,
      version: p.version,
      enabled: p.enabled,
      path: p.path,
    })),
    null,
    2
  )};

/**
 * Get plugin import path
 */
export function getPluginImportPath(pluginId: string): string {
  const plugin = pluginMetadata.find((p) => p.id === pluginId);
  if (!plugin) {
    throw new Error(\`Plugin "\${pluginId}" not found\`);
  }
  return \`@app/\${pluginId}\`;
}

/**
 * Check if plugin is discovered
 */
export function isPluginDiscovered(pluginId: string): boolean {
  return pluginMetadata.some((p) => p.id === pluginId);
}

/**
 * Get all enabled plugin IDs
 */
export function getEnabledPluginIds(): string[] {
  return pluginMetadata.filter((p) => p.enabled).map((p) => p.id);
}
`;

  fs.writeFileSync(outputPath, content);
  console.log(`📄 Generated: ${outputPath}`);

  return outputPath;
}

/**
 * Main function
 */
function main() {
  console.log('🚀 Plugin Discovery\n');

  const plugins = discoverPlugins();

  if (plugins.length === 0) {
    console.log('\n❌ No plugins discovered\n');
    process.exit(1);
  }

  console.log('\n' + '='.repeat(60));
  console.log(`\n📊 Summary:`);
  console.log(`   Total: ${plugins.length} plugins`);
  console.log(`   Enabled: ${plugins.filter((p) => p.enabled).length}`);
  console.log(`   Disabled: ${plugins.filter((p) => !p.enabled).length}`);

  // Generate manifest and imports
  generateManifest(plugins);
  generateImports(plugins);

  console.log('\n✅ Plugin discovery complete!\n');
}

main();
